### ISSUE TITLE
[MISC] Reordering translations to be in alphabetical order.

### ISSUE THREAD

**Issue by Farcasut** [xwikisas/application-analytics#36]
- Reorder the translations to be in alphabetical order.

**Comment by oanalavinia** [comment]
The idea behind the commits that start with a `[Misc]` is that you need to do some code changes that aren't actually linked to a bug / improvement / new feature, but mostly to some refactoring.

Now, what you enumerate above aren't actually all `[Misc]` changes. Only the translations part could be seen as refactoring. For the others, you should have a separate issue, maybe for `Improve analytics macros livedata UI`, since these changes will impact the UI. 

What you can do now is to update this issue to have it for the livedata UI updates (with an updated description, some screenshots) . After, you can keep the same PR for both, or have them separated if there are too many changes
